// ============================================================================
// WEAPONS DATA - ARC Raiders Wiki
// ============================================================================

export const weapons = [
  {
    id: "weapon_kettle",
    name: "Kettle",
    type: "Weapons",
    class: "Assault Rifle",
    rarity: "Common",
    value: [840, 2000, 3000, 5000],
    weight: 7,
    damage: 10,
    fireRate: 28,
    firingMode: "Semi-Automatic",
    range: "42.8",
    magazine: 20,
    ammo: "Light Ammo",
    dps: 280,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/c/c1/Kettle-Level1.png/160px-Kettle-Level1.png.webp",
    description: "Assault Rifle • Uses Light Ammo"
  },
  {
    id: "weapon_rattler",
    name: "Rattler",
    type: "Weapons",
    class: "Assault Rifle",
    rarity: "Common",
    value: [1750, 3000, 5000, 7000],
    weight: 6,
    damage: 9,
    fireRate: 33.3,
    firingMode: "Fully-Automatic",
    range: "56.2",
    magazine: 12,
    ammo: "Medium Ammo",
    dps: 300,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/b/be/Rattler-Level1.png/160px-Rattler-Level1.png.webp",
    description: "Assault Rifle • Uses Medium Ammo"
  },
  {
    id: "weapon_arpeggio",
    name: "Arpeggio",
    type: "Weapons",
    class: "Assault Rifle",
    rarity: "Uncommon",
    value: [5500, 8000, 11500, 15000],
    weight: 7,
    damage: 9.5,
    fireRate: 18.3,
    firingMode: "3-Round Burst",
    range: "55.9",
    magazine: 24,
    ammo: "Medium Ammo",
    dps: 174,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/6/6c/Arpeggio-Level1.png/160px-Arpeggio-Level1.png.webp",
    description: "Assault Rifle • Uses Medium Ammo"
  },
  {
    id: "weapon_tempest",
    name: "Tempest",
    type: "Weapons",
    class: "Assault Rifle",
    rarity: "Epic",
    value: [13000, 17000, 22000, 27000],
    weight: 11,
    damage: 10,
    fireRate: 36.7,
    firingMode: "Fully-Automatic",
    range: "55.9",
    magazine: 25,
    ammo: "Medium Ammo",
    dps: 367,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/c/c9/Tempest-Level1.png/160px-Tempest-Level1.png.webp",
    description: "Assault Rifle • Uses Medium Ammo"
  },
  {
    id: "weapon_bettina",
    name: "Bettina",
    type: "Weapons",
    class: "Assault Rifle",
    rarity: "Epic",
    value: [8000, 11000, 14000, 18000],
    weight: 11,
    damage: 14,
    fireRate: 32,
    firingMode: "Fully-Automatic",
    range: "51.3",
    magazine: 22,
    ammo: "Heavy Ammo",
    dps: 448,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/a/ac/Bettina.png/160px-Bettina.png.webp",
    description: "Assault Rifle • Uses Heavy Ammo"
  },
  {
    id: "weapon_ferro",
    name: "Ferro",
    type: "Weapons",
    class: "Battle Rifle",
    rarity: "Common",
    value: [475, 1000, 2000, 2900],
    weight: 8,
    damage: 40,
    fireRate: 6.6,
    firingMode: "Break-Action",
    range: "53.1",
    magazine: 1,
    ammo: "Heavy Ammo",
    dps: 264,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/b/b0/Ferro-Level1.png/160px-Ferro-Level1.png.webp",
    description: "Battle Rifle • Uses Heavy Ammo"
  },
  {
    id: "weapon_renegade",
    name: "Renegade",
    type: "Weapons",
    class: "Battle Rifle",
    rarity: "Rare",
    value: [7000, 10000, 13000, 17000],
    weight: 10,
    damage: 35,
    fireRate: 21,
    firingMode: "Lever-Action",
    range: "68.8",
    magazine: 8,
    ammo: "Medium Ammo",
    dps: 735,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/b/b5/Renegade-Level1.png/160px-Renegade-Level1.png.webp",
    description: "Battle Rifle • Uses Medium Ammo"
  },
  {
    id: "weapon_aphelion",
    name: "Aphelion",
    type: "Weapons",
    class: "Battle Rifle",
    rarity: "Legendary",
    value: [27500, 0, 0, 0],
    weight: 10,
    damage: 25,
    fireRate: 9,
    firingMode: "2-Round Burst",
    range: "76 [1]",
    magazine: 10,
    ammo: "Energy Clip",
    dps: 225,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/8/88/Aphelion.png/160px-Aphelion.png.webp",
    description: "Battle Rifle • Experimental"
  },
  {
    id: "weapon_stitcher",
    name: "Stitcher",
    type: "Weapons",
    class: "SMG",
    rarity: "Common",
    value: [800, 2000, 3000, 5000],
    weight: 5,
    damage: 7,
    fireRate: 45.3,
    firingMode: "Fully-Automatic",
    range: "42.1",
    magazine: 20,
    ammo: "Light Ammo",
    dps: 317,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/3/3a/Stitcher-Level1.png/160px-Stitcher-Level1.png.webp",
    description: "SMG • Uses Light Ammo"
  },
  {
    id: "weapon_bobcat",
    name: "Bobcat",
    type: "Weapons",
    class: "SMG",
    rarity: "Epic",
    value: [13000, 17000, 22000, 27000],
    weight: 7,
    damage: 6,
    fireRate: 66.7,
    firingMode: "Fully-Automatic",
    range: "44",
    magazine: 20,
    ammo: "Light Ammo",
    dps: 400,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/3/36/Bobcat-Level1.png/160px-Bobcat-Level1.png.webp",
    description: "SMG • Uses Light Ammo"
  },
  {
    id: "weapon_il_toro",
    name: "Il Toro",
    type: "Weapons",
    class: "Shotgun",
    rarity: "Uncommon",
    value: [5000, 7000, 10000, 13000],
    weight: 8,
    damage: 67.5,
    fireRate: 14.3,
    firingMode: "Pump-Action",
    range: "20",
    magazine: 5,
    ammo: "Shotgun Ammo",
    dps: 965,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/5/50/Il_Toro-Level1.png/160px-Il_Toro-Level1.png.webp",
    description: "Shotgun • Uses Shotgun Ammo"
  },
  {
    id: "weapon_vulcano",
    name: "Vulcano",
    type: "Weapons",
    class: "Shotgun",
    rarity: "Epic",
    value: [10000, 13000, 17000, 22000],
    weight: 8,
    damage: 49.5,
    fireRate: 26.3,
    firingMode: "Semi-Automatic",
    range: "26",
    magazine: 6,
    ammo: "Shotgun Ammo",
    dps: 1302,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/d/da/Vulcano-Level1.png/160px-Vulcano-Level1.png.webp",
    description: "Shotgun • Uses Shotgun Ammo"
  },
  {
    id: "weapon_hairpin",
    name: "Hairpin",
    type: "Weapons",
    class: "Pistol",
    rarity: "Common",
    value: [450, 1000, 2000, 2900],
    weight: 3,
    damage: 20,
    fireRate: 9,
    firingMode: "Slide-Action",
    range: "38.6",
    magazine: 8,
    ammo: "Light Ammo",
    dps: 180,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/6/65/Hairpin-Level1.png/160px-Hairpin-Level1.png.webp",
    description: "Pistol • Integrated Silencer"
  },
  {
    id: "weapon_burletta",
    name: "Burletta",
    type: "Weapons",
    class: "Pistol",
    rarity: "Uncommon",
    value: [2900, 5000, 7000, 10000],
    weight: 4,
    damage: 10,
    fireRate: 28,
    firingMode: "Semi-Automatic",
    range: "41.7",
    magazine: 12,
    ammo: "Light Ammo",
    dps: 280,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/d/d4/Burletta-Level1.png/160px-Burletta-Level1.png.webp",
    description: "Pistol • Uses Light Ammo"
  },
  {
    id: "weapon_venator",
    name: "Venator",
    type: "Weapons",
    class: "Pistol",
    rarity: "Rare",
    value: [7000, 10000, 13000, 17000],
    weight: 5,
    damage: 18,
    fireRate: 36.7,
    firingMode: "Semi-Automatic",
    range: "48.4",
    magazine: 10,
    ammo: "Medium Ammo",
    dps: 661,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/b/b4/Venator-Level1.png/160px-Venator-Level1.png.webp",
    description: "Pistol • Twin Shot"
  },
  {
    id: "weapon_anvil",
    name: "Anvil",
    type: "Weapons",
    class: "Hand Cannon",
    rarity: "Uncommon",
    value: [5000, 7000, 10000, 13000],
    weight: 5,
    damage: 40,
    fireRate: 16.3,
    firingMode: "Single-Action",
    range: "50.2",
    magazine: 6,
    ammo: "Heavy Ammo",
    dps: 652,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/0/00/Anvil-Level1.png/160px-Anvil-Level1.png.webp",
    description: "Hand Cannon • Uses Heavy Ammo"
  },
  {
    id: "weapon_torrente",
    name: "Torrente",
    type: "Weapons",
    class: "LMG",
    rarity: "Rare",
    value: [7000, 10000, 13000, 17000],
    weight: 12,
    damage: 8,
    fireRate: 58.3,
    firingMode: "Fully-Automatic",
    range: "49.9",
    magazine: 60,
    ammo: "Medium Ammo",
    dps: 466,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/1/1e/Torrente-Level1.png/160px-Torrente-Level1.png.webp",
    description: "LMG • Uses Medium Ammo"
  },
  {
    id: "weapon_osprey",
    name: "Osprey",
    type: "Weapons",
    class: "Sniper Rifle",
    rarity: "Rare",
    value: [7000, 10000, 13000, 17000],
    weight: 7,
    damage: 45,
    fireRate: 17.7,
    firingMode: "Bolt-Action",
    range: "80.3",
    magazine: 8,
    ammo: "Medium Ammo",
    dps: 797,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/a/ae/Osprey-Level1.png/160px-Osprey-Level1.png.webp",
    description: "Sniper Rifle • Scoped (5.66x zoom)"
  },
  {
    id: "weapon_jupiter",
    name: "Jupiter",
    type: "Weapons",
    class: "Sniper Rifle",
    rarity: "Legendary",
    value: [27500, 0, 0, 0],
    weight: 9,
    damage: 60,
    fireRate: 7.67,
    firingMode: "Bolt-Action",
    range: "71.7",
    magazine: 5,
    ammo: "Energy Clip",
    dps: 460,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/6/68/Jupiter.png/160px-Jupiter.png.webp",
    description: "Sniper Rifle • Experimental"
  },
  {
    id: "weapon_hullcracker",
    name: "Hullcracker",
    type: "Weapons",
    class: "Special",
    rarity: "Epic",
    value: [10000, 13000, 17000, 22000],
    weight: 7,
    damage: 100,
    fireRate: 20.3,
    firingMode: "Pump-Action",
    range: "38.9",
    magazine: 5,
    ammo: "Launcher Ammo",
    dps: 2030,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/b/ba/Hullcracker-Level1.png/160px-Hullcracker-Level1.png.webp",
    description: "Special • Uses Launcher Ammo"
  },
  {
    id: "weapon_equalizer",
    name: "Equalizer",
    type: "Weapons",
    class: "Special",
    rarity: "Legendary",
    value: [27500, 0, 0, 0],
    weight: 14,
    damage: 8,
    fireRate: 33.33,
    firingMode: "Fully-Automatic",
    range: null,
    magazine: 50,
    ammo: "Energy Clip",
    dps: 267,
    mods: "Unknown",
    imageUrl: "https://arcraiders.wiki/w/images/thumb/9/96/Equalizer.png/160px-Equalizer.png.webp",
    description: "Special • Uses Energy Clip"
  }
];
